version: '3.4'

services:
  ex1api:
    container_name: ex1_api
    image: ${DOCKER_REGISTRY-}ex1api
    restart: "no"
    build:
      context: .
      dockerfile: Ex1.API/Dockerfile
    expose:
      - "80" #http
      - "443" #https
    ports:
      - 5325:80
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=Ex1
      - DB_PASSWORD=root
      - DB_USER=root
  ex1websvelte:
    container_name: ex1_web_svelte
    image: ${DOCKER_REGISTRY-}ex1.web.svelte
    restart: "no"
    build:
      context: Ex1.Web/ex1-svelte
      dockerfile: Dockerfile
      args:
        - PUBLIC_API_PATH=http://localhost:5325/
    ports:
      - 5326:3000
    depends_on:
      - ex1api
    environment:
      - PORT=3000
  db:
    container_name: ex1_postgres_db
    image: hondeson/ex1-db-postgres:clean
    build:
      context: Ex1.Model
      dockerfile: Docker/Dockerfile-postgres
    restart: "no"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Ex1
    ports:
      - "5432:5432"
  pgadmin:
    container_name: ex1_pgadmin
    image: dpage/pgadmin4:6.14
    restart: "no"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
